### PR TITLE
Don't declare hashie gem as a dependency

### PR DESCRIPTION
**Pull request by buren**
Moves hashie gem to a development dependency.

### CODE REVIEW

**Comment by Albin-trialbee** [comment]
I think faraday might be dependent on it?

**Comment by buren** [comment]
Then shouldn't it be included automatically when installed?

**Comment by buren** [comment]
I can't find any mention of `Hashie` in [`faraday`](https://github.com/lostisland/faraday).

**Comment by buren** [comment]
Hm, I must say that I'm a bit confused I just found [mashify.rb](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/response/mashify.rb#L14) defined in `faraday_middleware`, though there is no reference to it in the README. 

So I guess your right, we need the `Hashie` gem :)

**Pull request closed without merging**
